hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_megatron_trainer
  - _self_

# config for the rollout (only for resource isolation)
rollout:
  # Number of nodes used in the rollout
  nnodes: 1
  # Number of GPUs per node
  n_gpus_per_node: 8